on:
  workflow_call:

jobs:
  deploy-maven-center:
    name: "🚀deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Decode gradle.properties
        run: |
          echo "signing.keyId=${{ secrets.GPG_KEY_ID }}" >> ~/.gradle/gradle.properties
          echo "signing.password=${{ secrets.GPG_PASSPHRASE }}" >> ~/.gradle/gradle.properties
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> ~/.gradle/gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> ~/.gradle/gradle.properties
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and sign artifacts
        run: ./gradlew clean build publishToMavenLocal sign

      - name: Publish to maven central
        run: ./gradlew publish
