name: "🔀CI on PR"
on:
  pull_request:
    branches:
      - main
      - release
jobs:
  ci:
    name: "🔨"
    uses: ./.github/workflows/ci-01-build.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
